Add failure notification job to Gradle data capturing samples nightly workflow
Signed-off-by: Gasper Kojek <gkojek@gradle.com>

diff --git a/.github/workflows/convention-develocity-shared-verification-nightly.yml b/.github/workflows/convention-develocity-shared-verification-nightly.yml
--- a/.github/workflows/convention-develocity-shared-verification-nightly.yml
+++ b/.github/workflows/convention-develocity-shared-verification-nightly.yml
@@ -71,5 +71,31 @@ jobs:
           DEVELOCITY_ACCESS_KEY: ${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}
       - name: Verify Build Scan published
         if: ${{ !steps.build.outputs.build-scan-url }}
-        run: echo "::error ::No Build Scan published"; exit 1          
+        run: echo "::error ::No Build Scan published"; exit 1
+
+  failure-notification:
+    name: Matrix failure notification
+    runs-on: ubuntu-latest
+    needs:
+      - build
+      - verification
+    if: failure()
+    steps:
+      - name: Get secrets
+        uses: gradle/actions-internal/get-aws-secrets@v1
+        with:
+          role-to-assume: arn:aws:iam::992382829881:role/GHASecrets_develocity-build-config-samples_all
+          secret-ids: |
+            DV_SOLUTIONS_SCHEDULED_WORKFLOWS_WEBHOOK_URL,gha/develocity-build-config-samples/_all/dv_solutions_scheduled_workflows_webhook_url
+      - name: Report scheduled workflow failure
+        uses: slackapi/slack-github-action@v2.1.1
+        with:
+          webhook: ${{ env.DV_SOLUTIONS_SCHEDULED_WORKFLOWS_WEBHOOK_URL }}
+          webhook-type: webhook-trigger
+          payload-templated: true
+          payload: |
+            {
+              "workflow_name": "Testing: Verify Gradle Data Capturing Samples (Nightly)",
+              "workflow_run_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+            }
 
